[Tussock Model]
nsims = 160
nthreads = 10
nyears = 250

[Paths]
output_dir = h3/repro_establish
subdir = resampled_fits
training_csv = ./input_data/tussock_density_tussock_diam.csv

[Resampling]
n_sets = 50
train_percent = 25
sample_with_replacement = true
random_seed = 123

[Optimization]
max_evals = 300
n_init = 5
tol_f = 1e-3
tol_x = 1e-3
init_log10_span = 1.0
step_frac = 0.2
step_abs = 0.3
optimize_log_space = false
cma_sigma = 0.5
cma_popsize = 12
cma_patience = 20

[Mechanisms]
; Format Example: S_R_E where:
;   S (Survival) = G (logit)
;   R (Reproduction) = G (logit)
;   E (Establishment) = L (linear)
;
; Letter key:
;   L = linear
;   G = logit
;   I = inverse
;   E = exponential
use_spatial_survival = true
use_spatial_reproduction = true
use_spatial_establishment = true
use_crowding_survival = false
use_crowding_reproduction = false
use_crowding_establishment = true
crowding_radius_cm = 2.0
spatial_survival_form = exponential
spatial_reproduction_form = exponential
spatial_establishment_form = exponential

[ParameterActivation]
optimize_leaf_offset = true
optimize_ks = true
optimize_kr = true
optimize_ke = true
optimize_bs = true
optimize_br = true
optimize_be = true
optimize_c_space_survival = true
optimize_c_space_reproduction = true
optimize_k_crowd_survival = false
optimize_k_crowd_reproduction = true
optimize_k_crowd_establishment = true

[Constraints]
extinction_weight = 0.0
constraint_year = 25
min_alive_tillers = 25
constraint_pass_frac = 0.8
alive_overflow_threshold = 500
overgrown_radius_threshold = 2.5
hard_fail_on_overflow = false
require_survive_to_end_for_fit = false
diameter_sd_weight = 1.0
leaf_bad_weight = 5.0
extinct_frac_weight = 5.0
overflow_frac_weight = 5.0

[Plotting]
plot_every = 1
plot_kde = false
print_fail_breakdown = false

